### ISSUE TITLE
The script does not find BCP files when running on Linux

### ISSUE THREAD

**Issue by 24mu13** [jbonfardeci/import-bacpac-powershell#3]
The files are extracted without taking in consideration the path delimiter ('/' in Linux other than '\')..

**Comment by jbonfardeci** [comment]
Thank you for reporting that. I wrote the program before PS was available on Linux and didn't consider it. I'll add a patch for it.

**Comment by 24mu13** [comment]
Please note, as part of this issue, we could also mention on README.md [mssql-tools18](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver16&tabs=redhat-install) as required package.

**Comment by jbonfardeci** [comment]
My time is limited. Would you like to be a contributor?

**Comment by jbonfardeci** [comment]
> Please note, as part of this issue, we could also mention on README.md [mssql-tools18](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver16&tabs=redhat-install) as required package.

Good point. I did include this in the readme "... data inserted into the target table via the BCP utility included with SSMS and SQL Server installations."

**Comment by 24mu13** [comment]
> My time is limited. Would you like to be a contributor?

My pleasure
